[module/clock]
type = internal/date
format-prefix = "%{T5}%{F#44112255}%{F-}%{T-}"
format-suffix = "%{T5}%{F#44112255}%{F-}%{T-}"
format-background = #44112255
interval = 1
;format-prefix = " "
;format-prefix-padding = 1
;format-prefix-margin = 1
;format-prefix-foreground = ${colors.darkgrey}
;format-prefix-background = ${colors.brown_t} 
;format-background = ${colors.darkbrown} 
format-padding=0
time = " %H:%M %"
label = %time%
