[module/clock]
type = internal/date
interval = 1
;format-prefix = " "
;format-prefix-padding = 1
;format-prefix-margin = 1
;format-prefix-foreground = ${colors.darkgrey}
;format-prefix-background = ${colors.brown_t} 
;format-background = ${colors.darkbrown} 
format-padding=0.5
time = " %H:%M %"
label = %time%
