[module/cpu]
type = internal/cpu
;format-prefix = " "
;format-prefix-foreground = ${colors.darkgrey}
;format-prefix-background = #7a4
;format-prefix-padding = 1
;format-prefix-margin = 1
format = <label> <ramp-coreload>
;format-foreground = ${colors.grey}
;format-background = #7a4
;format-background = ${colors.darkblue_t}
;format-background = ${colors.darkgrey_t}
format-padding = 1
label = "  %percentage%%"
ramp-coreload-spacing = 1
ramp-coreload-0 = %{F#0a0}▁%{F-}
ramp-coreload-1 = %{F#0a0}▂%{F-}
ramp-coreload-2 = %{F#0a0}▃%{F-}
ramp-coreload-3 = %{F#0a0}▄%{F-}
ramp-coreload-4 = %{F#f80}▅%{F-}
ramp-coreload-5 = %{F#f80}▆%{F-}
ramp-coreload-6 = %{F#f00}▇%{F-}
ramp-coreload-7 = %{F#f00}█%{F-}
