[module/date]
type = internal/date
;interval = 1
;format-prefix = ""
;format-prefix-padding = 1
;;format-prefix-margin = 1
;format-prefix-foreground = ${colors.white}
;format-prefix-background = ${colors.darkmagenta} 
;date = " %d.%m%"
;format-background = ${colors.darkmagenta} 
;format-padding=1
format-padding=0.5
format-margin = 0
date = " %d.%m "
label = %date%
