[module/dexcom]
type = custom/script
exec = ~/.config/polybar/scripts/dexcom.sh
interval = 1
; example nerd font icon
format-prefix = " "  
format = <label>
label = " %output% "
;format-padding = 1
;format-foreground = ${colors.white}
;format-background = ${colors.darkred-t}
