[module/filesystem]
type = internal/fs
interval = 46
format-mounted-background = ${colors.darkblue}
format-mounted-padding = 1
format-mounted-margin = 0
mount-0 = /mnt/samsung/web
mount-1 = /mnt/arbeit
;mount-2 = /home/ossi/Downloads/sys
mount-2 = /mnt/samsung/admin
;label-mounted = %{F#0a81f5} %mountpoint%%{F-}: %percentage_used%%
label-mounted = %fsname%: %percentage_used%%
;label-mounted-padding = 1
;format-margin = 1
