[module/fsroot]
type = internal/fs
interval = 46
;format-mounted-background = ${colors.darkblue}
;format-mounted-padding = 1
mount-0 = /
label-mounted = " %mountpoint%: %percentage_used%% "
format-background = ${colors.white_t}
