[module/lan]
type = custom/script
exec = ~/.config/polybar/scripts/ip.sh
;format-padding = 1
format-background = ${colors.darkgrey-t}
;#type = internal/network
;#interface = eno1
;format-connected-prefix = "  "
;format-connected-prefix-foreground = ${colors.grey}
;format-connected-prefix-background = ${colors.darkgreen}
format-prefix = ""
format-prefix-foreground = ${colors.grey}
format-prefix-background = ${colors.darkgreen}
;format-prefix-spacing = 2
;format-prefix-margin = 2
format-prefix-padding = 1
;#label-connected = "%ifname%: %local_ip%  | "
;label-connected-padding = 1
;label-connected = "%ifname%: %local_ip% %local_ip6% | "
;label-disconnected = "%ifname%: not connected | "
