[module/memory]
type = internal/memory
interval = 2
;format-prefix = "  "
;format-prefix-foreground = ${colors.darkgrey}
;format-prefix-background = #4bffdc
;format-prefix-background = ${colors.blue}
;format-background = ${colors.blue}
;format-padding=1
format-padding=0.5
label = "󰍛 %percentage_used%%  "
