[module/memory]
type = internal/memory
format-prefix = "%{T5}%{F#44112255}%{F-}%{T-}"
format-suffix = "%{T5}%{F#44112255}%{F-}%{T-}"
format-background = #44112255
interval = 2
;format-prefix = "  "
;format-prefix-foreground = ${colors.darkgrey}
;format-prefix-background = #4bffdc
;format-prefix-background = ${colors.blue}
;format-background = ${colors.blue}
;format-padding=1
format-padding=0
label = "󰍛 %percentage_used%%  "
