[module/title]
type = internal/xwindow
format-prefix = "  "
format-prefix-foreground = ${colors.darkgrey}
format-prefix-background = ${colors.primary}
label = %title:0:53:...%
;label-foreground = ${colors.lightblack}
label-foreground = ${colors.primary}
label-background = #aa212223
label-padding = 2
