; Polybar config - main variant

include-file = ~/.config/polybar/colors/colors.ini

[bar/top]
radius=10.0
;The first 2 characters stands for the amount of transparency.
;background = #11212223
background = #11000000

; Put the bar at the top of the screen
bottom = false
;height=26

;modules-left =  hdd filesystem
modules-center =   title
;modules-right = network-ip
;font-0 = RobotoMono Nerd Font:size=10;2
font-0 = "JetBrainsMono Nerd Font:size=12;2"
font-1 = Noto Sans Mono:style=Regular:size=16;2
font-2 = "Symbols Nerd Font:size=18;3"
;Symbols Nerd Font contains only the Powerline and Nerd Font icons.
;size=16 ensures they match the height of your other fonts.
;T2 tells Polybar to use font-2 for these modules.
override-redirect = true
enable-ipc = true


[bar/mybar]

;foreground = ${colors.black}
foreground = ${colors.lightgray}
;background = ${colors.white_t}
background = ${colors.black_t}

; Put the bar at the bottom of the screen
bottom = true
;height=36

modules-left = temp-colored network-ip fsadmin space fsroot space  memory cpu
modules-center = i3
;modules-right = dexcom fsadmin  fsroot memory weather date clock  pavol tray
modules-right = dexcom space weather space  date space  clock  pavol tray

font-0 = "Ubuntu Mono Bold Nerd Font:size=10;3"
font-1 = "Symbols Nerd Font:size=10;3"
font-2 = Noto Sans Mono:style=Regular

; --- Modules ---

include-file = ~/.config/polybar/modules/dexcom.ini
include-file = ~/.config/polybar/modules/weather.ini
include-file = ~/.config/polybar/modules/tray.ini
include-file = ~/.config/polybar/modules/memory.ini
include-file = ~/.config/polybar/modules/pavol.ini
include-file = ~/.config/polybar/modules/pulseaudio.ini
include-file = ~/.config/polybar/modules/title.ini
include-file = ~/.config/polybar/modules/clock.ini
include-file = ~/.config/polybar/modules/date.ini
include-file = ~/.config/polybar/modules/space.ini
include-file = ~/.config/polybar/modules/sep.ini
include-file = ~/.config/polybar/modules/hdd.ini
include-file = ~/.config/polybar/modules/fsroot.ini
include-file = ~/.config/polybar/modules/fsadmin.ini
include-file = ~/.config/polybar/modules/filesystem.ini
include-file = ~/.config/polybar/modules/cpu-temp.ini
include-file = ~/.config/polybar/modules/temp-colored.ini
include-file = ~/.config/polybar/modules/temperature.ini
include-file = ~/.config/polybar/modules/network-ip.ini
include-file = ~/.config/polybar/modules/lan.ini
include-file = ~/.config/polybar/modules/cpu.ini
include-file = ~/.config/polybar/modules/i3.ini
include-file = ~/.config/polybar/modules/wlan.ini
