[colors]
; transparency -> 00 full, FF opaque
white_t = #44eeeeee
black_t = #11000000
darkblue_t = #44112255
darkgrey_t = #99212223
;darkgreen-t= #99003300
darkgreen_t= #44002300
brown_t=#997d7858
darkbrown_t=#55391f00
darkmagenta_t = #bb332425

black = #000
lightblack=#111
white = #fff
lightgray=#ddd
grey = #aaa
darkgrey = #555
red = #a00
darkred = #610000
darkorange=#593100
orange=#896433
green = #0f0
darkgreen=#030
darkergreen=#002800
darkblue=#125
blue=#0a81f5
brown=#7d7858
darkbrown=#391f00
darkmagenta=#332425
;gentoo
;background = ${xrdb:color0:#222}
background = #222
background-alt = #444
;foreground = ${xrdb:color7:#222}
foreground = #dfdfdf
foreground-alt = #555
primary = #ffb52a
secondary = #e60053
alert = #bd2c40
